### ISSUE TITLE
Alignment slightly off on mobile

### ISSUE THREAD

**Issue by SimenB** [jest-website-migration/jest#3]
![Screenshot_20201204-132402](https://user-images.githubusercontent.com/1404810/101163644-2d3b6a80-3634-11eb-972e-c3cfdcc97e5c.png)

**Comment by slorber** [comment]
I think it's fixed, probably by @simek ?

**Comment by SimenB** [comment]
No, this is still broken

![image](https://user-images.githubusercontent.com/1404810/101815386-bdd7e600-3b1f-11eb-81a2-7926313d3e8f.png)

**Comment by slorber** [comment]
yeah you are right, it fails on production build due to css ordering

added a fix, should be fine in next redeploy

**Comment by SimenB** [comment]
yep, correct now 👍

**Comment by SimenB** [comment]
>it fails on production build due to css ordering

seems like a bug somewhere in the build chain tho, no?

**Comment by slorber** [comment]
it's just the css pipeline is not strictly identical for dev server and production

can't really do anything about it but at some point, it would be nice to cleanup a bit the existing Jest CSS

now you can use scss, and css modules, so it may help to have more modular css in the future and ensure global naming conflicts and css order issues
