### ISSUE TITLE
API Reference pages have broken TOCs

### ISSUE THREAD

**Issue by orta** [jest-website-migration/jest#6]
Compare:

  - https://deploy-preview-1--jest-v2.netlify.app/docs/api#methods
  - vs https://jestjs.io/docs/en/api

  It's basically a C&P of that sidebar at the top

**Comment by slorber** [comment]
Thanks, didn't even know we had this in v1 😅

**Comment by slorber** [comment]
Will be fixed on next deploy, using new v2 feature: https://github.com/facebook/docusaurus/pull/3904

![image](https://user-images.githubusercontent.com/749374/101928371-cab71100-3bd5-11eb-829b-34e8846b232f.png)
