### ISSUE TITLE
Split sidebar in 2: Docs + API ?

### ISSUE THREAD

**Issue by slorber** [jest-website-migration/jest#9]
The Jest v1 navbar highlighting is a bit weird currently, as it is highlighted only on the first link of the sidebar, not the 2nd.

![image](https://user-images.githubusercontent.com/749374/101363506-c6bb8400-38a1-11eb-88b3-6e99fecec558.png)

 
![image](https://user-images.githubusercontent.com/749374/101363638-ebaff700-38a1-11eb-980f-6019a0f00a55.png)

@simek and I think it would be better to handle this like RN website, and have the navbar item behaves more like a "tab".

![image](https://user-images.githubusercontent.com/749374/101363760-0edaa680-38a2-11eb-8e7e-3293726fb013.png)

This requires to split the sidebar in 2 (docs + API) so that each navbar item is associated to a distinct sidebar, and we can highlight. (With 1 sidebar, it would require maintaining a list of all URL regexp, less maintainable).

**Comment by slorber** [comment]
@orta do you approve this change?

(we can use RN tab design, or keep the existing green box)

**Comment by orta** [comment]
This feels like a good call to me :+1:

**Comment by slorber** [comment]
Thanks @orta 

I've implemented the behavior change here (no design yet), let me know if this looks good to you.
https://deploy-preview-10--jest-v2.netlify.app/

https://github.com/jest-website-migration/jest/pull/10
